[package]
name = "async-arc-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", default-features = false, features = ["sync", "macros", "rt"] }
thiserror = "1.0.30"